[tools]
go = "1.24"
staticcheck = "latest"

[tasks.default]
description = "Builds and tests the library"
depends = ["lint", "test"]

[tasks.test]
description = "Run the unit test suite"
env.CGO_ENABLED = 1                                    # Required for -race
run = ["go test -race -covermode=atomic -cover ./..."]

[tasks.integration_test]
description = "Run the integration test suite"
run = ["go test --tags='integration' ./..."]

[tasks.lint]
run = ["go vet ./...", "staticcheck ./..."]
